---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: order
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: batchusivaji/argorepo:dev_9
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: "64Mi"
            limits:
              cpu: 200m
              memory: "128Mi"
